# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7bffb8330ae4f8bb83f40f8b35a4f37da94f7abb17dea5863b6c7848a45168be894bde1aed2f5e4abade2d910bc07083013b079069ac73ebd3ec608c94d82bc6

test:
  secret_key_base: e2d1ed1ab55e0384acf518804bbec2e0639630df0623ab761c7ce66c49e04bd8922ad86ccac75c1beba4f5eb75b1fc03110ca829ae6be7d0c217cd267d672584

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: zczcs64654zsczc654szc
